### ISSUE TITLE
Sample.Mail memory leak

### ISSUE THREAD

**Issue by ersin-ertan** [sockeqwe/mosby#90] opened 2015-09-30 15:13 UTC
```
2.0.1-SNAPSHOT:201.
* com.hannesdorfmann.mosby.sample.mail.MainActivity has leaked:
* GC ROOT android.os.ResultReceiver$MyResultReceiver.this$0
* references android.app.ExitTransitionCoordinator.mActivity
* leaks com.hannesdorfmann.mosby.sample.mail.MainActivity instance
```
To reproduce the leak: click on a piece of mail, the circular loading animation will start, and rotate the device prior to the mail load. (Rotate roughly 5 times without pause)

**Comment by ersin-ertan** [comment] 2015-09-30 15:24
Note that going clicking on a person to see all past mail interactions made then clicking back, then attempting to reproduce the error does not cause a leak. The difference is that the detail portion on the right, does not load, instead the layout is set as the full screen of the mail stream.

This leads me to believe that the leak is from of the detail portion.

**Comment by sockeqwe** [comment] 2015-09-30 20:39
I think it's a problem with my custom ActivityTransitionAnimation. I don't have much time right now to check that, but I'm pretty sure that this is the problem since I hold a hard reference to a View that will be animated (shared element). Hence the view's parent activity can not be garbage collected --> memory leak

Can you reproduce this issue on a pre Android 5.0 device?

**Comment by ersin-ertan** [comment] 2015-09-30 21:21
Attempt device 4.1.1 no leak.

For future reference, with pre 5.0 there is a 'LEAK CAN BE IGNORED' WriteActivity leak.

**Comment by sockeqwe** [comment] 2015-10-01 05:18
'LEAK CAN BE IGNORED' is a leak caused internaly by android itself

**Comment by dimsuz** [comment] 2016-05-23 12:54
Shouldn't this issue be closed then? :)

Leak can be ignored usually means it's some system bug or other non-controllable thing.

**Comment by sockeqwe** [comment] 2016-05-23 13:02
If I remember correctly, the leak is caused by an custom ActivityTransition. So the leak is not caused by Mosby, but the demo's custom activity transition should be fixed  ... so little time so much to do ...

**Comment by ersin-ertan** [comment] 2016-05-24 01:35
The WriteActivity leak was an additional leak not regarding the ActivityTransitionAnimation. 
I wanted to put it out there as supplementary information to rule out what it wasn't.

**Comment by sockeqwe** [comment] 2016-05-24 11:06
Thanks for the clarification. In that case this can be closed.

**Closed by sockeqwe** 2016-05-24 11:06 UTC
Labels: example
